export const FETCH_MYCHAT_REQUEST = "FETCH_MYCHAT_REQUEST";
export const FETCH_MYCHAT_SUCCESS = "FETCH_MYCHAT_SUCCESS";
export const FETCH_MYCHAT_FAILURE = "FETCH_MYCHAT_FAILURE";

export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAILURE = "CREATE_CHAT_FAILURE";

export const SELECTED_CHAT = "SELECTED_CHAT";
