export const FETCH_SESSION_REQUEST = " FETCH_SESSION_REQUEST";
export const FETCH_SESSION_SUCCESS = " FETCH_SESSION_SUCCESS";
export const FETCH_SESSION_FAILURE = " FETCH_SESSION_FAILURE";

export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAILURE = "CREATE_SESSION_FAILURE";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAILURE = "UPDATE_SESSION_FAILURE";

export const FETCH_SESSIONBY_ID_REQUEST = " FETCH_SESSIONBY_ID_REQUEST";
export const FETCH_SESSIONBY_ID_SUCCESS = " FETCH_SESSIONBY_ID_SUCCESS";
export const FETCH_SESSIONBY_ID_FAILURE = " FETCH_SESSIONBY_ID_FAILURE";

export const SET_SESSION_FORMDATA = "SET_SESSION_FORMDATA";
