export const SELECTED_SUBCATEGORY = "SELECTED_SUBCATEGORY";

export const FETCH_ALL_SUBCATEGORY_REQUEST = "FETCH_ALL_SUBCATEGORY_REQUEST";
export const FETCH_ALL_SUBCATEGORY_SUCCESS = "FETCH_ALL_SUBCATEGORY_SUCCESS";
export const FETCH_ALL_SUBCATEGORY_FAILURE = "FETCH_ALL_SUBCATEGORY_FAILURE";
