export const SET_SELECTED_SME = "SET_SELECTED_SME";
export const GET_ALL_MATCHING_SME_REQUEST = "GET_ALL_MATCHING_SME_REQUEST";
export const GET_ALL_MATCHING_SME_SUCCESS = "GET_ALL_MATCHING_SME_SUCCESS";
export const GET_ALL_MATCHING_SME_FAILURE = "GET_ALL_MATCHING_SME_FAILURE";

export const GET_USER_BYID_REQUEST = "GET_USER_BYID_REQUEST";
export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS";
export const GET_USER_BYID_FAILURE = "GET_USER_BYID_FAILURE";

export const GET_ALL_SME_REQUEST = "GET_ALL_SME_REQUEST";
export const GET_ALL_SME_SUCCESS = "GET_ALL_SME_SUCCESS";
export const GET_ALL_SME_FAILURE = "GET_ALL_SME_FAILURE";
