import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Example from "./components/Header/Header";
import HeroSection from "./components/HeroSection/HeroSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Example></Example>
        {children}
      </body>
    </html>
  );
}
