import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Header from "./components/Header/Header";
import HeroSection from "./components/HeroSection/HeroSection";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full w-full`}>
        <Providers>
          {/* example as header */}
          <div style={{ zIndex: 999 }} className="fixed w-full">
            <Header />
          </div>

          {children}
        </Providers>
      </body>
    </html>
  );
}
